"""empty message

Revision ID: 155135504d6b
Revises: bec454d1063b
Create Date: 2024-04-13 15:28:45.814865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155135504d6b'
down_revision = 'bec454d1063b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
